### ISSUE TITLE
插件能否支持gbk(gb18030)解码

### ISSUE THREAD

**Issue by ouyang1989** [xulihang/capacitor-plugin-dynamsoft-barcode-reader#1]
目前使用的二维码中，包规以及物料名称等信息是中文显示，但是用该插件不能正确解析中文，也没有看到相应的参数设置，后续能否支持，或者有没有其他的方式，能正确解析中文

**Comment by xulihang** [comment]
可以用barcodebytesbase64自己做编码转换
