### ISSUE TITLE
插件第一次进入扫码界面白屏

### ISSUE THREAD

**Issue by ouyang1989** [xulihang/capacitor-plugin-dynamsoft-barcode-reader#2]
插件使用问题：在软件第一次安装，第一次进入扫码界面的时候，会出现白屏，后面再次进入之后就不会，这个问题是什么原因产生的，需要怎么去解决

**Comment by xulihang** [comment]
进入界面前有请求相机权限吗

**Comment by ouyang1989** [comment]
有请求权限的，允许之后，界面是白屏。用capacitor-qr-code-scanner-master这个例子跑起来也是有这个问题。手机型号是HUAWEI HLK-AL00 安卓系统是10.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2023年8月7日(星期一) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tony-xlh/capacitor-plugin-dynamsoft-barcode-reader] 插件第一次进入扫码界面白屏 (Issue #2)





 
进入界面前有请求相机权限吗

**Comment by xulihang** [comment]
需要用这个接口先请求一次，不然获取权限后相机没有打开：https://github.com/tony-xlh/capacitor-plugin-dynamsoft-barcode-reader#requestcamerapermission

**Comment by ouyang1989** [comment]
我试了一下，这个接口获取权限之后，不能马上进入扫码界面，马上进入的话，也还是白屏。实际测试在登录界面获取相机权限，到业务界面之后就能正常使用扫码功能。如果在业务界面，直接获取权限，然后进入扫码的话，还是一样的白屏

**Comment by xulihang** [comment]
用await等待获取权限完成后再startscan应该就可以了

**Comment by ouyang1989** [comment]
用await也不行，这个问题不影响使用，知道怎么处理就行，只是如果内部能解决掉，会更完美，总体来讲，这个控件还是很好用的

**Comment by xulihang** [comment]
插件更新了，应该没有这个问题了。
